apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: sre-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.10.1
          command:
            - sh
            - -c
            - |
              while true; do
                date
                curl -s -o /dev/null -w "checkout-service status: %{http_code}\n" http://checkout-service
                sleep 2
              done
