apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sre-demo
  annotations:
    kubernetes.io/change-cause: "Bad deploy: wrong Redis image tag"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:this-tag-does-not-exist
          ports:
            - containerPort: 6379
